services:
  korat-simulator:
    image: ghcr.io/martinpestanar/koratflow-dino:latest
    volumes:
      - .:/app
    working_dir: /app
    command: python thermal_simulator.py

  korat-validator:
    image: ghcr.io/martinpestanar/koratflow-dino:latest
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - korat-simulator
    command: python validador_integridad.py

  korat-hmi:
    image: ghcr.io/martinpestanar/koratflow-dino:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - korat-simulator
    command: streamlit run hmi_dashboard.py --server.port 8501 --server.address 0.0.0.0
